### ISSUE TITLE
VM-Aligned Policy and Constraint Adjustments

### ISSUE THREAD

**Issue by C2100-PR** [C2100-PR/cloud-operations#3]
# Policy and Constraint Adjustments for VM Setup

## Current VM Configuration
- Project: api-for-warp-drive
- VM: warpdrive01-prod
- Region: us-west1
- Using internal IPs for secure operations

### 1. Firewall Rules Alignment
```yaml
firewall-rules:
  internal-allow:
    direction: INGRESS
    source_ranges: [10.0.0.0/8]
    allow:
      - protocol: tcp
      - protocol: udp
  ingress-from-gke:
    direction: INGRESS
    source_tags: ['gke-nodes']
```

### 2. Constraint Removals
Remove the following constraints that are no longer needed with VM setup:
- constraints/compute.vmExternalIpAccess
- constraints/compute.restrictVpcPeering

### 3. Network Policy Updates
```yaml
network-policies:
  allow-internal:
    ingress:
      from:
        - ipBlock:
            cidr: 10.0.0.0/8
  allow-gke:
    ingress:
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gke-system
```

### 4. Service Account Permissions
Ensure service accounts have necessary permissions for internal networking:
- compute.networks.use
- container.clusters.get
- logging.logEntries.create

## Implementation Steps
1. Remove external IP constraints
2. Update firewall rules
3. Configure network policies
4. Verify service account permissions

## Verification
- Test internal communication between VM and GKE
- Verify no external IP constraints blocking operations
- Confirm logging and monitoring functionality

Please update this issue once the policy adjustments are implemented and verified.
